services:
  tracking_server:
    restart: always
    image: ${APP_IMAGE:-compose-services-app}
    networks:
      - backend
    ports:
      - "5000:5000"
    environment:
      - BACKEND_URI=postgresql://postgres:password@postgres:5432/mlflow_db
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
      - MLFLOW_S3_IGNORE_TLS=true
    depends_on:
      - postgres
      - minio
volumes:
  postgres_data:
  minio_data:
networks:
  backend:
    driver: bridge